name: Build and run tests

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-22.04']
        cc: [ 'gcc', 'clang' ]
    name: Compile via CMakeLists.txt on ${{ matrix.os }} using ${{ matrix.cc }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libsdl1.2-dev
      - run: cmake .
      - run: make
  make:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-22.04']
        makefile: ['makefile']
    name: Compile via ${{ matrix.os }} on ${{ matrix.os }}
    env:
      BRANDY_BUILD_FLAGS: "-Wextra"
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libsdl1.2-dev
      - run: make -f ${{ matrix.makefile }}
  make_text:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-22.04']
        makefile: ['makefile.text']
    name: Compile via ${{ matrix.makefile }} Makefile on ${{ matrix.os }}
    env:
      BRANDY_BUILD_FLAGS: "-Wextra"
    steps:
      - uses: actions/checkout@v2
      - run: make -f ${{ matrix.makefile }}
      - run: make -f ${{ matrix.makefile }} test
  make_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-14', 'macos-13']
        makefile: ['build/makefile.macosx.text']
    name: Compile via ${{ matrix.makefile }} Makefile on ${{ matrix.os }}
    env:
      BRANDY_BUILD_FLAGS: "-Wextra"
    steps:
      - uses: actions/checkout@v2
      - run: make -f ${{ matrix.makefile }} all
      - run: make -f ${{ matrix.makefile }} test
